# Generated by Django 2.0.6 on 2019-05-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190510_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_name',
        ),
    ]
