# Generated by Django 2.1.7 on 2019-05-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190510_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=23, verbose_name='NID')),
                ('nid_front', models.ImageField(upload_to=users.models.upload_pic_to, verbose_name='NID Front Picture')),
                ('nid_back', models.ImageField(upload_to=users.models.upload_pic_to, verbose_name='NID Back Picture')),
                ('nid_selfie', models.ImageField(upload_to=users.models.upload_pic_to, verbose_name='Selfie With Holding Your NID')),
                ('utility', models.ImageField(upload_to=users.models.upload_pic_to, verbose_name='Utility Picture')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_verify_submit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nid_back',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nid_front',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nid_selfie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='utility',
        ),
    ]
