# Generated by Django 2.0.2 on 2019-04-13 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dropcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropcycle',
            name='drop_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
