# Generated by Django 2.1.7 on 2019-05-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gps_lat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='gps_lon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='near_by',
            field=models.CharField(blank=True, max_length=30, verbose_name='2nd area'),
        ),
        migrations.AlterField(
            model_name='location',
            name='near_by_t',
            field=models.CharField(blank=True, max_length=30, verbose_name='3rd area'),
        ),
    ]
