# Generated by Django 2.1.7 on 2019-05-12 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_auto_20190513_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropcycle',
            name='cycle_id',
        ),
        migrations.RemoveField(
            model_name='dropcycle',
            name='drop_by',
        ),
        migrations.AddField(
            model_name='cycle',
            name='pick_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dropcycle',
            name='pick_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycles.Pickcycle'),
        ),
        migrations.AlterField(
            model_name='dropcycle',
            name='drop_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pickcycle',
            name='pick_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
