# Generated by Django 2.0.2 on 2019-04-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_auto_20190410_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='isDroped',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='state',
        ),
    ]
