# Generated by Django 2.1.7 on 2019-05-17 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_auto_20190517_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='rating',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
