# Generated by Django 2.1.7 on 2019-05-17 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0005_auto_20190517_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
