# Generated by Django 2.0.2 on 2019-04-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20181223_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationId',
            field=models.CharField(choices=[('001', 'L1'), ('002', 'L2'), ('003', 'L3'), ('004', 'L4'), ('005', 'L5'), ('006', 'L6'), ('007', 'L7'), ('008', 'L8')], max_length=255),
        ),
    ]
